# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b74ee767d011d8b1307980456ed5843d1ccd5873b59bd9ae37b26b6ebd6b944d27dc68c1bc4bfd984a7195565e78658723a49359bbde12cd8085c3e3e19125f

test:
  secret_key_base: 91683045bf90e67514ce68c5e66c8de234dca5fa70785a7c37dfd487dc44321f6666d3e6ec5243c91f12d545b1c3a1b4b8475c9e887c911b2c37fa48f7993cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
